name: dronerus
favicon: null
layout_spectrum: 0.99503
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.741428917972371
  lightness: 0.029713054420426488
  saturation: 0.8547793687321246
  rhythmicContrast: 0.45440604304894805
purpose: []
