name: "drone R'us"
favicon: null
layout_spectrum: 0.95129
typography_spectrum: 1
title: "drone R'us"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbef'
    - '#010101'
    - '#e43d2b'
    - '#c6b36f'
    - '#686147'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
